# Generated by Django 3.2.4 on 2021-06-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210618_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruit',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='name',
            new_name='title',
        ),
    ]
