# Generated by Django 3.2.4 on 2021-06-18 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210618_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruit',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='provider',
            old_name='title',
            new_name='name',
        ),
    ]
