# Generated by Django 3.2.4 on 2021-06-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210618_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='name',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
